### ISSUE TITLE
KIP-827 support

### ISSUE THREAD

**Issue by SamBarker** [strimzi/kafka-quotas-plugin#28]
[KIP-827](https://cwiki.apache.org/confluence/display/KAFKA/KIP-827%3A+Expose+log+dirs+total+and+usable+space+via+Kafka+API): Expose log dirs total and usable space via Kafka API was included in the Kafka 3.3 series and should support everything the plug-in needs to provide throttling based on volume consumption. 

It should be possible to detect if programmatically if KIP-827 is available on a given Kafka cluster thus enable the support for it conditionally and preserve the existing behaviour for backwards compatibility with earlier Kafka releases.

**Comment by k-wall** [comment]
Does strimzi have a precedent for maintaining plugin compatibility?  I mean KIP-827 has brought DescribeLogDirs RPC  change which meant a Java API change LogDirDescription.     Will the code in kafka-quotas-plugin need to be written in such a way to avoid a dependency on the new methods (i.e. reflection) so that the plugin still works with older Kafka brokers built containing the older Kafka client?

**Comment by scholzj** [comment]
@k-wall I'm not sure what kind of compatibility you mean here. If you mean that the plugin will use calls available only from a new Kafka version, that has in general two solutions:
* If the behaviour of the plugin does nto change by this, the new version can be included only in the new Kafka version and the old version can use the old version.
* If the whole plugin changes in what it does and how it behaves, we might not want to have different versions in different Kafka versions. So we can wait until the old Kafka versions not supporting the API are not supported anymore.

**Comment by SamBarker** [comment]
I think this is now resolved on main.
